version: "3.9"

services:
  eureka-server:
    build: ./discovery-server/naming-server
    platform: linux/amd64
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  config-server:
    build: ./config-server/config-server
    platform: linux/amd64
    container_name: config-server
    restart: always
    ports:
      - "8086:8086"
    networks:
      - microservices-network
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka

  postgres-db-users-api:
    image: postgres:15
    container_name: postgres-db-users-api
    restart: always
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: login
      POSTGRES_DB: login_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservices-network

  mongodb-projects:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: freelaif_db
      MONGO_INITDB_ROOT_USERNAME: freelaif
      MONGO_INITDB_ROOT_PASSWORD: freelaif
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - microservices-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  users-api:
    build: ./users-api
    platform: linux/amd64
    container_name: users-api-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_started
      postgres-db-users-api:
        condition: service_started
    networks:
      - microservices-network
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - CONFIG_SERVER=http://config-server:8086

  spring-projects-api:
    build: ./project
    platform: linux/amd64
    container_name: spring-projects-api-container
    restart: always
    ports:
      - "8101:8101"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_started
      mongodb-projects:
        condition: service_healthy
    networks:
      - microservices-network
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - CONFIG_SERVER=http://config-server:8086

volumes:
  pgdata:
  mongo-data:

networks:
  microservices-network:
    external: true
