services:
  users-api:
    build: .
    restart: always
    container_name: users-api-container
    ports:
      - 8080:8080
    depends_on:
      - postgres-db-users-api
    networks:
      - microservices-network

    environment:
      - EUREKA_SERVER=http://localhost:8761/eureka

  postgres-db-users-api:
    image: postgres:15
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: login
      POSTGRES_DB: login_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true

volumes:
  pgdata: