version: "3.9"

services:

  spring-projects-api:
    build: .
    restart: always
    ports:
      - "8101:8101"
    networks:
      - microservices-network
    depends_on:
      mongodb-projects:
        condition: service_healthy

  mongodb-projects:
    image: mongo:7.0
    #container_name: mongodb-container
    restart: always
    environment:
      MONGO_INITDB_DATABASE: freelaif_db
      MONGO_INITDB_ROOT_USERNAME: freelaif
      MONGO_INITDB_ROOT_PASSWORD: freelaif
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

volumes:
  mongo-data:

networks:
  microservices-network:
    external: true
